import type { Metadata } from "next";
import Header from "@/components/layout/header/header";
import "../app/styles/App.scss";
import Hero from "@/app/hero/hero";
import LogoSlider from "./logoSlider/logoSlider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Hero/>
        <LogoSlider/>
        {children}
      </body>
    </html>
  );
}
